#!/usr/bin/env python3
"""Generate the human-readable converter catalog from structured data."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "data" / "converters.json"
OUTPUT_FILE = ROOT / "CATALOG.md"

CATEGORY_LABELS = {
    "archive": "Archives",
    "audio": "Audio",
    "data": "Structured data and spreadsheets",
    "document": "Documents",
    "ebook": "E-books",
    "image": "Images",
    "presentation": "Presentations",
    "video": "Video",
}


def display_flag(value: str) -> str:
    return {"yes": "Yes", "no": "No", "limited": "Limited", "mixed": "Mixed", "optional": "Optional", "unknown": "Unknown"}.get(value, value)


def format_list(values: list[str]) -> str:
    return ", ".join(f"`{value.upper()}`" for value in values)


def main() -> None:
    payload = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    converters = payload["converters"]
    lines = [
        "# File Converter Catalog",
        "",
        "> Generated from [`data/converters.json`](data/converters.json). Do not edit this file directly.",
        "",
        f"**{len(converters)} verified converters** across **{len(CATEGORY_LABELS)} categories**.",
        "",
        "## Categories",
        "",
    ]

    for category, label in CATEGORY_LABELS.items():
        count = sum(category in item["categories"] for item in converters)
        anchor = label.lower().replace(" ", "-").replace("-and-", "-and-")
        lines.append(f"- [{label}](#{anchor}) ({count})")

    lines.extend([
        "",
        "## Legend",
        "",
        "- **Local:** Conversion runs on your device rather than requiring a file upload.",
        "- **Free:** `Yes` means normal conversion is available without payment; `Limited` means usage restrictions apply.",
        "- **Formats:** Input and output coverage is directional and does not imply that every input converts to every output.",
        "",
    ])

    for category, label in CATEGORY_LABELS.items():
        members = [item for item in converters if category in item["categories"]]
        lines.extend([
            f"## {label}",
            "",
            "| Converter | Type | Free | Local | Batch | Coverage |",
            "|---|---|---:|---:|---:|---|",
        ])
        for item in members:
            tool_types = " / ".join(value.replace("-", " ").title() for value in item["types"])
            if "many" in item["inputs"] or "many" in item["outputs"]:
                format_summary = "Broad; see evidence"
            else:
                format_summary = f"{len(item['inputs'])} inputs / {len(item['outputs'])} outputs"
            lines.append(
                f"| [{item['name']}]({item['url']}) ([formats]({item['documentation_url']})) "
                f"| {tool_types} | {display_flag(item['free'])} | {display_flag(item['local_processing'])} "
                f"| {display_flag(item['batch'])} | {format_summary} |"
            )
        lines.extend(["", "[Back to categories](#categories)", ""])

    lines.extend([
        "## Full records",
        "",
    ])
    for item in converters:
        lines.extend([
            f"### {item['name']}",
            "",
            item["notes"],
            "",
            f"- **Website:** [{item['url']}]({item['url']})",
            f"- **Format evidence:** [{item['documentation_url']}]({item['documentation_url']})",
            f"- **Inputs:** {format_list(item['inputs'])}",
            f"- **Outputs:** {format_list(item['outputs'])}",
            f"- **Platforms:** {', '.join(item['platforms'])}",
            f"- **Free:** {display_flag(item['free'])}",
            f"- **Account required:** {display_flag(item['account_required'])}",
            f"- **Local processing:** {display_flag(item['local_processing'])}",
            f"- **Open source:** {display_flag(item['open_source'])}",
            f"- **Batch:** {display_flag(item['batch'])}",
            f"- **Watermark:** {display_flag(item['watermark'])}",
            f"- **Last verified:** {item['last_verified']}",
            "",
        ])

    OUTPUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT_FILE.relative_to(ROOT)} with {len(converters)} converters")


if __name__ == "__main__":
    main()
